--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-30-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------
GRANT CREATE TABLE TO flow;
  CREATE TABLE "FLOW"."BOARD" 
   (	"ID" NUMBER(19,0), 
	"AUTHOR" VARCHAR2(100 BYTE), 
	"DEPARTMENT" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"VIEW_COUNT" NUMBER(10,0) DEFAULT 0, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE, 
	"BOARD_TYPE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SYSTEM"."BOARD"."DEPARTMENT" IS '부서명';
   COMMENT ON COLUMN "SYSTEM"."BOARD"."TITLE" IS '제목';
   COMMENT ON COLUMN "SYSTEM"."BOARD"."CONTENT" IS '내용';
   COMMENT ON COLUMN "SYSTEM"."BOARD"."VIEW_COUNT" IS '조회수';
   COMMENT ON COLUMN "SYSTEM"."BOARD"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "SYSTEM"."BOARD"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "SYSTEM"."BOARD"."BOARD_TYPE" IS '게시판 타입';
--------------------------------------------------------
--  DDL for Index ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ID" ON "SYSTEM"."BOARD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOARD" ADD CONSTRAINT "ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BOARD" ADD CONSTRAINT "CORETIME_CHK1" CHECK (BOARD_TYPE IN ('NOTICE', 'GENERAL')) ENABLE;
