CREATE TABLE users
(
    name VARCHAR2(50) NOT NULL,
	id VARCHAR2(50) NOT NULL,
	password VARCHAR2(255) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    tel VARCHAR2(50) NOT NULL,
    rank VARCHAR2(50) NOT NULL,
    department VARCHAR2(50) NOT NULL,
    birth DATE NOT NULL,
    updatedAt DATE DEFAULT SYSDATE NOT NULL,
    createdAt DATE DEFAULT SYSDATE NOT NULL,
    role VARCHAR2(10)
);

ALTER TABLE users ADD CONSTRAINT uk_users_id UNIQUE (id);

INSERT INTO USERS (NAME, ID, PASSWORD, EMAIL, TEL, RANK, DEPARTMENT, BIRTH, ROLE)
        VALUES ('관리자', 'admin', '1234', 'jack981109@naver.com', '010-6230-1825', '관리자', '관리자', '1998-11-09', 'ROLE_ADMIN');
