--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-30-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "FLOW"."USERS" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TEL" VARCHAR2(50 BYTE), 
	"RANK" VARCHAR2(50 BYTE), 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"BIRTH" DATE, 
	"UPDATEDAT" DATE DEFAULT SYSDATE, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USERS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOW"."UK_USERS_ID" ON "FLOW"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "FLOW"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("DEPARTMENT" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("UPDATEDAT" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" MODIFY ("CREATEDAT" NOT NULL ENABLE);
  ALTER TABLE "FLOW"."USERS" ADD CONSTRAINT "UK_USERS_ID" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
